version: '3.4'

services:
  jobfind:
    image: ${DOCKER_REGISTRY-}jobfind
    build:
      context: .
      dockerfile: JobFind/Dockerfile


      
  mongo:
    image: mongo
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
      #- ./data:/data/db
    ports:
      - "27017:27017"

  
     


